version: '3.7'
services:
    sample-nuxt:
        container_name: nuxt
        ports: 
            - 3100:3000
            - 9229:9229
        build: ./docker
        volumes: 
            - ./app:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        logging:
            driver: json-file
            options:
                max-file: '1'
                max-size: 3m
        tty: true
        stdin_open: true
        environment: 
            - ports=3000
            - CHOKIDAR_USEPOLLING=true
            - HOST=0.0.0.0
volumes:
    node_modules:
